export interface CatalogItem {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  price: number;
  salePrice: number | null;
  sku: string;
  category: {
    id: string;
    name: string;
    slug: string;
  };
  universe: "JEWELRY" | "BEAUTY_SKIN_HAIR";
  subCategory: string;
  brand: string;
  stock: number;
  isPublished: boolean;
  isFeatured: boolean;
  tags: string[];
  images: Array<{
    id: string;
    url: string;
    alt?: string;
    isPrimary?: boolean;
    sortOrder?: number;
  }>;
  sellerId?: string;
  sellerName?: string;
  sellerShopName?: string;
  sellerBasePrice?: number;
  adminProfitMargin?: number;
  createdAt: string;
}

export const UNIVERSES = [
  {
    id: "ALL",
    name: "All Creations",
    shortName: "All",
    icon: "✨",
    slug: "all",
    description: "The complete atelier collection of fine ornaments and silk beauty",
  },
  {
    id: "JEWELRY",
    name: "Fine Jewellery & Pearls",
    shortName: "Fine Jewellery",
    icon: "💎",
    slug: "fine-jewelry",
    description: "18K & 22K gold-plated bridal chokers, freshwater baroque pearls & zircon solitaires",
  },
  {
    id: "BEAUTY_SKIN_HAIR",
    name: "Silk Skincare, Facewash & Hair",
    shortName: "Skincare & Hair",
    icon: "🌸",
    slug: "beauty-skin-hair",
    description: "Botanical facewashes, bio-silk peptide serums & Moroccan argan hair elixirs",
  },
] as const;

export const JEWELRY_SUB_CATEGORIES = [
  "All Jewels",
  "Chokers & Necklaces",
  "Earrings & Jhumkas",
  "Rings & Solitaires",
  "Bridal Sets & Bangles",
] as const;

export const BEAUTY_SUB_CATEGORIES = [
  "All Beauty",
  "Facewash & Cleansers",
  "Silk Serums & Glow",
  "Hair Oils & Elixirs",
  "Luxe Lip Care",
] as const;

// 22 Pure Authentic Veloura Creations using ONLY valid beauty & jewelry images (item-01 to item-86)
export const VELOURA_AUTHENTIC_PRODUCTS: CatalogItem[] = [
  {
    id: "prod-01",
    name: "Veloura Velvet Matte Lip Casket — 6 Luxe Shades",
    slug: "veloura-velvet-matte-lip-casket-6-luxe-shades",
    description: "An opulent collection of 6 feather-weight velvet matte liquid silks in iconic ruby, berry, and nude rose hues. Enriched with botanical jojoba oil and vitamin E for 16-hour comfort without feathering.",
    shortDescription: "An opulent boxed casket of 6 feather-light velvet matte liquid lip silks in royal ruby, berry, and nude rose hues.",
    price: 2990,
    salePrice: 2450,
    sku: "VEL-LIP-SET-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 35,
    isPublished: true,
    isFeatured: true,
    tags: ["Lipstick", "Matte", "Best Seller", "Velvet Silk", "Trending"],
    images: [
      { id: "p1-1", url: "/uploads/products/item-01.jpeg", alt: "Lip Casket", isPrimary: true, sortOrder: 0 },
      { id: "p1-2", url: "/uploads/products/item-02.jpeg", alt: "Shade Palette", isPrimary: false, sortOrder: 1 },
      { id: "p1-3", url: "/uploads/products/item-03.jpeg", alt: "Velvet Swatches", isPrimary: false, sortOrder: 2 },
      { id: "p1-4", url: "/uploads/products/item-04.jpeg", alt: "Presentation Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 2100,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-02",
    name: "24K Gold Starlight Pavé Zircon Choker & Earrings Set",
    slug: "24k-gold-starlight-pave-zircon-choker-earrings-set",
    description: "Handcrafted 18K gold-plated bridal soiree choker encrusted with high-fire pavé cubic zircon stones and matching drop earrings. Tarnish-free, hypoallergenic, and crafted for royal celebrations.",
    shortDescription: "Handcrafted 18K gold-plated bridal choker encrusted with high-fire pavé cubic zircon stones and matching earrings.",
    price: 5200,
    salePrice: 4450,
    sku: "VEL-JWL-SET-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Chokers & Necklaces",
    brand: "VELOURA Haute Atelier",
    stock: 18,
    isPublished: true,
    isFeatured: true,
    tags: ["Jewelry", "Choker", "18K Gold", "Bridal", "Zircon"],
    images: [
      { id: "p2-1", url: "/uploads/products/item-05.jpeg", alt: "Gold Choker Set", isPrimary: true, sortOrder: 0 },
      { id: "p2-2", url: "/uploads/products/item-06.jpeg", alt: "Earrings Detail", isPrimary: false, sortOrder: 1 },
      { id: "p2-3", url: "/uploads/products/item-07.jpeg", alt: "Pavé Stones", isPrimary: false, sortOrder: 2 },
      { id: "p2-4", url: "/uploads/products/item-08.jpeg", alt: "Velvet Casket", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 3800,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-03",
    name: "Haute Shimmer Rose Gold Highlighter & Blush Glow Palette",
    slug: "haute-shimmer-rose-gold-highlighter-blush-palette",
    description: "Micro-milled baked rose pearl pigments that melt into the skin for an ethereal glass-skin radiance. Features 4 versatile shades for cheekbones, brow bones, and décolletage.",
    shortDescription: "Micro-milled baked rose pearl pigments that melt effortlessly into the skin for an ethereal glass-skin radiance.",
    price: 2350,
    salePrice: 1950,
    sku: "VEL-GLW-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 35,
    isPublished: true,
    isFeatured: true,
    tags: ["Highlighter", "Blush", "Rose Gold", "Glow"],
    images: [
      { id: "p3-1", url: "/uploads/products/item-09.jpeg", alt: "Glow Palette", isPrimary: true, sortOrder: 0 },
      { id: "p3-2", url: "/uploads/products/item-10.jpeg", alt: "Swatches", isPrimary: false, sortOrder: 1 },
      { id: "p3-3", url: "/uploads/products/item-11.jpeg", alt: "Packaging", isPrimary: false, sortOrder: 2 },
      { id: "p3-4", url: "/uploads/products/item-12.jpeg", alt: "Mirror Compact", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1700,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-04",
    name: "Imperial Baroque Freshwater Pearl & Emerald Drop Necklace",
    slug: "imperial-baroque-freshwater-pearl-emerald-drop-necklace",
    description: "Organic baroque freshwater pearls strung with 22K gold-plated accents and an emerald-cut radiant hydrothermal crystal pendant. A royal Pakistani heirloom piece inspired by Lahore heritage.",
    shortDescription: "Organic baroque freshwater pearls strung with 22K gold-plated accents and an emerald-cut crystal pendant.",
    price: 6450,
    salePrice: 5490,
    sku: "VEL-PRL-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Chokers & Necklaces",
    brand: "VELOURA Haute Atelier",
    stock: 15,
    isPublished: true,
    isFeatured: true,
    tags: ["Pearls", "Emerald", "Luxury", "Royal Collection"],
    images: [
      { id: "p4-1", url: "/uploads/products/item-13.jpeg", alt: "Pearl Necklace", isPrimary: true, sortOrder: 0 },
      { id: "p4-2", url: "/uploads/products/item-14.jpeg", alt: "Emerald Pendant", isPrimary: false, sortOrder: 1 },
      { id: "p4-3", url: "/uploads/products/item-15.jpeg", alt: "Baroque Details", isPrimary: false, sortOrder: 2 },
      { id: "p4-4", url: "/uploads/products/item-16.jpeg", alt: "Silk Case", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 4750,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-05",
    name: "Pure Damask Rose & Silk Peptide Dewy Setting Mist",
    slug: "pure-damask-rose-silk-peptide-dewy-setting-mist",
    description: "Steam-distilled Damask rosewater infused with silk peptides, niacinamide, and hyaluronic acid. Locks makeup in place while imparting an instant dewy glow and calming redness.",
    shortDescription: "Steam-distilled Damask rosewater infused with silk peptides, niacinamide, and hyaluronic acid for an instant dewy glow.",
    price: 1850,
    salePrice: 1550,
    sku: "VEL-MST-01",
    category: { id: "cat-3", name: "Silk Skincare & Glow", slug: "silk-skincare" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Silk Serums & Glow",
    brand: "VELOURA Haute Atelier",
    stock: 45,
    isPublished: true,
    isFeatured: false,
    tags: ["Skincare", "Rosewater", "Mist", "Silk Peptide", "Glow"],
    images: [
      { id: "p5-1", url: "/uploads/products/item-17.jpeg", alt: "Rose Mist", isPrimary: true, sortOrder: 0 },
      { id: "p5-2", url: "/uploads/products/item-18.jpeg", alt: "Bottle Spray", isPrimary: false, sortOrder: 1 },
      { id: "p5-3", url: "/uploads/products/item-19.jpeg", alt: "Dewy Glow", isPrimary: false, sortOrder: 2 },
      { id: "p5-4", url: "/uploads/products/item-20.jpeg", alt: "Ingredients", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1350,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-06",
    name: "Veloura Signature Gold Flake Hydrating Lip Treatment Oil",
    slug: "veloura-signature-gold-flake-hydrating-lip-treatment-oil",
    description: "Suspended 24K gold nano-flakes in organic cold-pressed rosehip, camellia, and sweet almond oils. Softens dry lips and provides a non-sticky glassy sheen with a subtle petal tint.",
    shortDescription: "Suspended 24K gold nano-flakes in organic cold-pressed rosehip, camellia, and sweet almond oils.",
    price: 1450,
    salePrice: 1250,
    sku: "VEL-OIL-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 60,
    isPublished: true,
    isFeatured: true,
    tags: ["Lip Oil", "24K Gold", "Hydration", "Gloss"],
    images: [
      { id: "p6-1", url: "/uploads/products/item-21.jpeg", alt: "Gold Lip Oil", isPrimary: true, sortOrder: 0 },
      { id: "p6-2", url: "/uploads/products/item-22.jpeg", alt: "Wand Applicator", isPrimary: false, sortOrder: 1 },
      { id: "p6-3", url: "/uploads/products/item-23.jpeg", alt: "Glass Glow", isPrimary: false, sortOrder: 2 },
      { id: "p6-4", url: "/uploads/products/item-24.jpeg", alt: "Packaging", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1050,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-07",
    name: "Celestial Solitaire Crown Ring & Eternity Chevron Band",
    slug: "celestial-solitaire-crown-ring-eternity-band",
    description: "A dazzling 2-carat diamond-brilliant round cut cubic zirconia nestled in a micro-pavé 18K gold band with matching nesting eternity chevron band. Hypoallergenic and scratch-resistant.",
    shortDescription: "A dazzling 2-carat diamond-brilliant round cut cubic zirconia nestled in a micro-pavé 18K gold band.",
    price: 2890,
    salePrice: 2450,
    sku: "VEL-RNG-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Rings & Solitaires",
    brand: "VELOURA Haute Atelier",
    stock: 25,
    isPublished: true,
    isFeatured: false,
    tags: ["Ring", "Zirconia", "18K Gold Plated", "Gift for Her"],
    images: [
      { id: "p7-1", url: "/uploads/products/item-25.jpeg", alt: "Solitaire Ring", isPrimary: true, sortOrder: 0 },
      { id: "p7-2", url: "/uploads/products/item-26.jpeg", alt: "Chevron Band", isPrimary: false, sortOrder: 1 },
      { id: "p7-3", url: "/uploads/products/item-27.jpeg", alt: "Side Profile", isPrimary: false, sortOrder: 2 },
      { id: "p7-4", url: "/uploads/products/item-28.jpeg", alt: "Velvet Ring Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 2100,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-08",
    name: "Moroccan Cashmere Silk Nourishing Hair Oil Elixir",
    slug: "moroccan-cashmere-silk-nourishing-hair-oil-elixir",
    description: "Liquid gold hair elixir formulated with Moroccan argan oil, keratin hydrolysate, and damask rose oil. Protects from heat styling up to 230°C and leaves hair like pure spun silk.",
    shortDescription: "Liquid gold hair elixir formulated with Moroccan argan oil, keratin hydrolysate, and damask rose oil.",
    price: 2650,
    salePrice: 2190,
    sku: "VEL-HAIR-02",
    category: { id: "cat-4", name: "Hair Elixirs & Fragrance", slug: "hair-fragrance" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Hair Oils & Elixirs",
    brand: "VELOURA Haute Atelier",
    stock: 30,
    isPublished: true,
    isFeatured: true,
    tags: ["Hair Serum", "Argan Oil", "Cashmere Silk", "Heat Protectant"],
    images: [
      { id: "p8-1", url: "/uploads/products/item-29.jpeg", alt: "Hair Elixir", isPrimary: true, sortOrder: 0 },
      { id: "p8-2", url: "/uploads/products/item-30.jpeg", alt: "Dropper Bottle", isPrimary: false, sortOrder: 1 },
      { id: "p8-3", url: "/uploads/products/item-31.jpeg", alt: "Texture", isPrimary: false, sortOrder: 2 },
      { id: "p8-4", url: "/uploads/products/item-32.jpeg", alt: "Silk Results", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1900,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-09",
    name: "Midnight Jasmine & Velvet Amber Hair Perfume Mist",
    slug: "midnight-jasmine-velvet-amber-hair-perfume-mist",
    description: "An intoxicating alcohol-free hair mist enriched with provitamin B5 and sensory extracts of Sambac jasmine, cashmere musk, and warm amber. Lasts over 24 hours in the hair breeze.",
    shortDescription: "An intoxicating alcohol-free hair mist enriched with provitamin B5 and sensory extracts of Sambac jasmine.",
    price: 2250,
    salePrice: 1890,
    sku: "VEL-PERF-01",
    category: { id: "cat-4", name: "Hair Elixirs & Fragrance", slug: "hair-fragrance" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Hair Oils & Elixirs",
    brand: "VELOURA Haute Atelier",
    stock: 28,
    isPublished: true,
    isFeatured: false,
    tags: ["Fragrance", "Hair Mist", "Jasmine", "Amber"],
    images: [
      { id: "p9-1", url: "/uploads/products/item-33.jpeg", alt: "Hair Perfume", isPrimary: true, sortOrder: 0 },
      { id: "p9-2", url: "/uploads/products/item-34.jpeg", alt: "Fragrance Bottle", isPrimary: false, sortOrder: 1 },
      { id: "p9-3", url: "/uploads/products/item-35.jpeg", alt: "Gold Cap", isPrimary: false, sortOrder: 2 },
      { id: "p9-4", url: "/uploads/products/item-36.jpeg", alt: "Gift Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1650,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    name: "Baroque Pearl Tassel Drop Earrings in 18K Gold Vermeil",
    slug: "baroque-pearl-tassel-drop-earrings-18k-gold-vermeil",
    description: "Lustrous organic baroque freshwater pearls suspended from 18K gold vermeil geometric links. Perfect statement piece for sangeet nights and reception banquets.",
    shortDescription: "Lustrous organic baroque freshwater pearls suspended from 18K gold vermeil geometric links.",
    price: 3450,
    salePrice: 2890,
    sku: "VEL-EAR-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Earrings & Jhumkas",
    brand: "VELOURA Haute Atelier",
    stock: 22,
    isPublished: true,
    isFeatured: true,
    tags: ["Earrings", "Pearls", "18K Gold Vermeil", "Statement"],
    images: [
      { id: "p10-1", url: "/uploads/products/item-37.jpeg", alt: "Pearl Earrings", isPrimary: true, sortOrder: 0 },
      { id: "p10-2", url: "/uploads/products/item-38.jpeg", alt: "Side Detail", isPrimary: false, sortOrder: 1 },
      { id: "p10-3", url: "/uploads/products/item-39.jpeg", alt: "Worn Look", isPrimary: false, sortOrder: 2 },
      { id: "p10-4", url: "/uploads/products/item-40.jpeg", alt: "Jewelry Pouch", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 2500,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Bio-Fermented Silk Peptide Dew Facial Serum",
    slug: "bio-fermented-silk-peptide-dew-facial-serum",
    description: "Pure liquid silk hydrolysate combined with 2% encapsulated multi-molecular hyaluronic acid and fermented camellia oil. Penetrates deeply to restore skin elasticity and create a porcelain dewy glass finish.",
    shortDescription: "Pure liquid silk hydrolysate combined with 2% encapsulated multi-molecular hyaluronic acid.",
    price: 2750,
    salePrice: 2290,
    sku: "VEL-SER-01",
    category: { id: "cat-3", name: "Silk Skincare & Glow", slug: "silk-skincare" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Silk Serums & Glow",
    brand: "VELOURA Haute Atelier",
    stock: 40,
    isPublished: true,
    isFeatured: true,
    tags: ["Serum", "Silk Peptides", "Glass Skin", "Anti-Aging"],
    images: [
      { id: "p11-1", url: "/uploads/products/item-41.jpeg", alt: "Silk Serum", isPrimary: true, sortOrder: 0 },
      { id: "p11-2", url: "/uploads/products/item-42.jpeg", alt: "Texture Pipette", isPrimary: false, sortOrder: 1 },
      { id: "p11-3", url: "/uploads/products/item-43.jpeg", alt: "Skin Absorption", isPrimary: false, sortOrder: 2 },
      { id: "p11-4", url: "/uploads/products/item-44.jpeg", alt: "Clinical Results", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1980,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Veloura Signature Pavé Diamond Tennis Bracelet",
    slug: "veloura-signature-pave-diamond-tennis-bracelet",
    description: "A continuous strand of hand-selected diamond-cut cubic zirconia in four-prong 18K yellow gold plated settings. Double security clasp for comfortable everyday sparkle.",
    shortDescription: "A continuous strand of hand-selected diamond-cut cubic zirconia in four-prong 18K yellow gold settings.",
    price: 4500,
    salePrice: 3850,
    sku: "VEL-BRC-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Bridal Sets & Bangles",
    brand: "VELOURA Haute Atelier",
    stock: 20,
    isPublished: true,
    isFeatured: true,
    tags: ["Tennis Bracelet", "Diamonds", "Gold Plated", "Wrist Luxury"],
    images: [
      { id: "p12-1", url: "/uploads/products/item-45.jpeg", alt: "Tennis Bracelet", isPrimary: true, sortOrder: 0 },
      { id: "p12-2", url: "/uploads/products/item-46.jpeg", alt: "Clasp Detail", isPrimary: false, sortOrder: 1 },
      { id: "p12-3", url: "/uploads/products/item-47.jpeg", alt: "Wrist Fit", isPrimary: false, sortOrder: 2 },
      { id: "p12-4", url: "/uploads/products/item-48.jpeg", alt: "Velvet Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 3300,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-13",
    name: "Hydrating Petal Flush Cheek & Lip Tint — Crimson Rose",
    slug: "hydrating-petal-flush-cheek-lip-tint-crimson-rose",
    description: "A water-gel buildable cheek and lip stain formulated with organic pomegranate extract, aloe vera, and beetroot anthocyanins. Creates a vibrant flushed glow that won't smudge.",
    shortDescription: "A water-gel buildable cheek and lip stain formulated with organic pomegranate extract and aloe vera.",
    price: 1350,
    salePrice: 1100,
    sku: "VEL-TNT-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 50,
    isPublished: true,
    isFeatured: false,
    tags: ["Lip Tint", "Cheek Stain", "Natural Flush", "Hydrating"],
    images: [
      { id: "p13-1", url: "/uploads/products/item-49.jpeg", alt: "Lip & Cheek Tint", isPrimary: true, sortOrder: 0 },
      { id: "p13-2", url: "/uploads/products/item-50.jpeg", alt: "Blush Swatch", isPrimary: false, sortOrder: 1 },
      { id: "p13-3", url: "/uploads/products/item-51.jpeg", alt: "Lip Application", isPrimary: false, sortOrder: 2 },
      { id: "p13-4", url: "/uploads/products/item-52.jpeg", alt: "Bottles", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 950,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-14",
    name: "24K Gold Kundan Meenakari Chandbali Earrings",
    slug: "24k-gold-kundan-meenakari-chandbali-earrings",
    description: "Royal Mughal crescent earrings crafted in 24K gold foil with hand-carved Jadau Kundan and emerald green enamel. Accented with miniature cultured pearl tassels.",
    shortDescription: "Royal Mughal crescent earrings crafted in 24K gold foil with hand-carved Jadau Kundan and emerald enamel.",
    price: 4200,
    salePrice: 3490,
    sku: "VEL-CND-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Earrings & Jhumkas",
    brand: "VELOURA Haute Atelier",
    stock: 16,
    isPublished: true,
    isFeatured: true,
    tags: ["Chandbali", "Kundan", "Meenakari", "Bridal Earrings"],
    images: [
      { id: "p14-1", url: "/uploads/products/item-53.jpeg", alt: "Chandbali", isPrimary: true, sortOrder: 0 },
      { id: "p14-2", url: "/uploads/products/item-54.jpeg", alt: "Enamel Work", isPrimary: false, sortOrder: 1 },
      { id: "p14-3", url: "/uploads/products/item-55.jpeg", alt: "Pearl Tassels", isPrimary: false, sortOrder: 2 },
      { id: "p14-4", url: "/uploads/products/item-56.jpeg", alt: "Earring Pair", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 3000,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    name: "Damask Rose Gentle Foaming Facewash & Deep Cleanser",
    slug: "damask-rose-gentle-foaming-facewash-deep-cleanser",
    description: "A sulfate-free, pH-balanced cloud foaming facewash steam-distilled from organic Damask rose petals and green tea hydrosol. Dissolves pollution, makeup, and oil without drying.",
    shortDescription: "A sulfate-free, pH-balanced cloud foaming facewash steam-distilled from organic Damask rose petals.",
    price: 1850,
    salePrice: 1490,
    sku: "VEL-CLN-01",
    category: { id: "cat-3", name: "Silk Skincare & Glow", slug: "silk-skincare" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Facewash & Cleansers",
    brand: "VELOURA Haute Atelier",
    stock: 55,
    isPublished: true,
    isFeatured: true,
    tags: ["Facewash", "Rose Water", "Cleanser", "Hydrating Wash"],
    images: [
      { id: "p15-1", url: "/uploads/products/item-01.jpeg", alt: "Rose Facewash", isPrimary: true, sortOrder: 0 },
      { id: "p15-2", url: "/uploads/products/item-17.jpeg", alt: "Foam Texture", isPrimary: false, sortOrder: 1 },
      { id: "p15-3", url: "/uploads/products/item-18.jpeg", alt: "Dispenser Pump", isPrimary: false, sortOrder: 2 },
      { id: "p15-4", url: "/uploads/products/item-19.jpeg", alt: "Packaging", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1250,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-16",
    name: "Royal Mughal Jadau Kundan Meenakari Choker & Jhumka Set",
    slug: "royal-mughal-jadau-kundan-meenakari-choker-jhumka-set",
    description: "Exquisite hand-painted pink Meenakari reverse with Jadau Kundan work on gold foil setting, completed with freshwater pearl cascades. The crown jewel of wedding season.",
    shortDescription: "Exquisite hand-painted pink Meenakari reverse with Jadau Kundan work on gold foil setting.",
    price: 7200,
    salePrice: 5990,
    sku: "VEL-ROYAL-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Bridal Sets & Bangles",
    brand: "VELOURA Haute Atelier",
    stock: 12,
    isPublished: true,
    isFeatured: true,
    tags: ["Kundan", "Meenakari", "Bridal Set", "Royal Jewellery"],
    images: [
      { id: "p16-1", url: "/uploads/products/item-61.jpeg", alt: "Kundan Choker Set", isPrimary: true, sortOrder: 0 },
      { id: "p16-2", url: "/uploads/products/item-62.jpeg", alt: "Jhumka Earrings", isPrimary: false, sortOrder: 1 },
      { id: "p16-3", url: "/uploads/products/item-63.jpeg", alt: "Meenakari Reverse", isPrimary: false, sortOrder: 2 },
      { id: "p16-4", url: "/uploads/products/item-64.jpeg", alt: "Bridal Velvet Casket", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 5100,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-17",
    name: "Luminous Silk Body Shimmer Dry Oil — Diamond Rose",
    slug: "luminous-silk-body-shimmer-dry-oil-diamond-rose",
    description: "Fast-absorbing luxurious dry body oil infused with diamond mineral shimmer, marula oil, and French vanilla fragrance. Gives an all-over goddess glow without staining clothes.",
    shortDescription: "Fast-absorbing luxurious dry body oil infused with diamond mineral shimmer, marula oil, and French vanilla.",
    price: 2750,
    salePrice: 2250,
    sku: "VEL-BDY-01",
    category: { id: "cat-3", name: "Silk Skincare & Glow", slug: "silk-skincare" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Silk Serums & Glow",
    brand: "VELOURA Haute Atelier",
    stock: 26,
    isPublished: true,
    isFeatured: false,
    tags: ["Body Oil", "Shimmer", "Glow", "French Vanilla"],
    images: [
      { id: "p17-1", url: "/uploads/products/item-65.jpeg", alt: "Shimmer Body Oil", isPrimary: true, sortOrder: 0 },
      { id: "p17-2", url: "/uploads/products/item-66.jpeg", alt: "Shimmer Dropper", isPrimary: false, sortOrder: 1 },
      { id: "p17-3", url: "/uploads/products/item-67.jpeg", alt: "Skin Swatch", isPrimary: false, sortOrder: 2 },
      { id: "p17-4", url: "/uploads/products/item-68.jpeg", alt: "Bottle in Sunlight", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 1900,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-18",
    name: "Oud & Rose Damascena Royal Hair & Body Elixir",
    slug: "oud-rose-damascena-royal-hair-body-elixir",
    description: "An opulent fusion of Cambodian oud and Taif rose essential oils. Nourishes the scalp, scents hair for 24+ hours, and calms frizz while creating a captivating sillage.",
    shortDescription: "An opulent fusion of Cambodian oud and Taif rose essential oils.",
    price: 3100,
    salePrice: 2650,
    sku: "VEL-OUD-01",
    category: { id: "cat-4", name: "Hair Elixirs & Fragrance", slug: "hair-fragrance" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Hair Oils & Elixirs",
    brand: "VELOURA Haute Atelier",
    stock: 20,
    isPublished: true,
    isFeatured: true,
    tags: ["Oud", "Damask Rose", "Perfume Oil", "Luxury Hair"],
    images: [
      { id: "p18-1", url: "/uploads/products/item-69.jpeg", alt: "Oud & Rose Elixir", isPrimary: true, sortOrder: 0 },
      { id: "p18-2", url: "/uploads/products/item-70.jpeg", alt: "Amber Glass", isPrimary: false, sortOrder: 1 },
      { id: "p18-3", url: "/uploads/products/item-71.jpeg", alt: "Dropper", isPrimary: false, sortOrder: 2 },
      { id: "p18-4", url: "/uploads/products/item-72.jpeg", alt: "Luxury Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 2200,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-19",
    name: "Dainty Evil Eye & Pearl Charm Layering Necklace",
    slug: "dainty-evil-eye-pearl-charm-layering-necklace",
    description: "18K gold-plated double-strand layering necklace featuring a sapphire-blue mother-of-pearl evil eye talisman and miniature freshwater pearl droplets. Elegant everyday protection.",
    shortDescription: "18K gold-plated double-strand layering necklace featuring a sapphire-blue mother-of-pearl evil eye talisman.",
    price: 2290,
    salePrice: 1950,
    sku: "VEL-EVL-01",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Chokers & Necklaces",
    brand: "VELOURA Haute Atelier",
    stock: 34,
    isPublished: true,
    isFeatured: false,
    tags: ["Evil Eye", "Layering Necklace", "Protection", "Pearls"],
    images: [
      { id: "p19-1", url: "/uploads/products/item-73.jpeg", alt: "Evil Eye Necklace", isPrimary: true, sortOrder: 0 },
      { id: "p19-2", url: "/uploads/products/item-74.jpeg", alt: "Charm Detail", isPrimary: false, sortOrder: 1 },
      { id: "p19-3", url: "/uploads/products/item-75.jpeg", alt: "Layered Look", isPrimary: false, sortOrder: 2 },
      { id: "p19-4", url: "/uploads/products/item-76.jpeg", alt: "Gift Pouch", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 1650,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-20",
    name: "Atelier Silk Touch Beauty Blender & Velvet Powder Puff Trio",
    slug: "atelier-silk-touch-beauty-blender-velvet-powder-puff-trio",
    description: "Ultra-plush hydrophilic polyurethane cosmetic sponges paired with triangular velvet powder puffs for streak-free airbrushed foundation and baking application.",
    shortDescription: "Ultra-plush hydrophilic polyurethane cosmetic sponges paired with triangular velvet powder puffs.",
    price: 1150,
    salePrice: 950,
    sku: "VEL-ACC-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 75,
    isPublished: true,
    isFeatured: false,
    tags: ["Sponges", "Beauty Blender", "Puff", "Makeup Tools"],
    images: [
      { id: "p20-1", url: "/uploads/products/item-77.jpeg", alt: "Beauty Blender Trio", isPrimary: true, sortOrder: 0 },
      { id: "p20-2", url: "/uploads/products/item-78.jpeg", alt: "Velvet Puff", isPrimary: false, sortOrder: 1 },
      { id: "p20-3", url: "/uploads/products/item-79.jpeg", alt: "Texture", isPrimary: false, sortOrder: 2 },
      { id: "p20-4", url: "/uploads/products/item-80.jpeg", alt: "Case", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 800,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-21",
    name: "Emerald & Baguette Crystal Statement Cocktail Ring",
    slug: "emerald-baguette-crystal-statement-cocktail-ring",
    description: "A bold emerald-cut hydrothermal green quartz bordered with tapered baguette micro-crystals on an adjustable 18K gold band. Turns heads at every dinner and wedding.",
    shortDescription: "A bold emerald-cut hydrothermal green quartz bordered with tapered baguette micro-crystals.",
    price: 2550,
    salePrice: 2190,
    sku: "VEL-RNG-02",
    category: { id: "cat-2", name: "Fine Jewelry & Pearls", slug: "fine-jewelry" },
    universe: "JEWELRY",
    subCategory: "Rings & Solitaires",
    brand: "VELOURA Haute Atelier",
    stock: 28,
    isPublished: true,
    isFeatured: true,
    tags: ["Ring", "Emerald Cut", "Cocktail Ring", "Statement"],
    images: [
      { id: "p21-1", url: "/uploads/products/item-81.jpeg", alt: "Cocktail Ring", isPrimary: true, sortOrder: 0 },
      { id: "p21-2", url: "/uploads/products/item-82.jpeg", alt: "Baguette Cut", isPrimary: false, sortOrder: 1 },
      { id: "p21-3", url: "/uploads/products/item-83.jpeg", alt: "Band Adjustment", isPrimary: false, sortOrder: 2 },
      { id: "p21-4", url: "/uploads/products/item-84.jpeg", alt: "Velvet Ring Box", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-seller-1",
    sellerName: "Lahore Heritage Pearls & Jewels",
    sellerShopName: "Lahore Heritage Jewels",
    sellerBasePrice: 1850,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-22",
    name: "Veloura Velvet Keepsake Luxury Gift Box & Hamper Deal",
    slug: "veloura-velvet-keepsake-luxury-gift-box-hamper-deal",
    description: "The ultimate luxury present: includes Velvet Lip Casket, Starlight Earrings, Silk Glow Serum, and a handcrafted silk rose in an embossed crimson velvet presentation box with complimentary gold ribboning.",
    shortDescription: "The ultimate luxury present: includes Velvet Lip Casket, Starlight Earrings, and Silk Glow Serum in a velvet box.",
    price: 650,
    salePrice: 590,
    sku: "VEL-GFT-01",
    category: { id: "cat-1", name: "Luxe Makeup & Lips", slug: "luxe-makeup" },
    universe: "BEAUTY_SKIN_HAIR",
    subCategory: "Luxe Lip Care",
    brand: "VELOURA Haute Atelier",
    stock: 15,
    isPublished: true,
    isFeatured: true,
    tags: ["Gift Box", "Hamper", "Velvet Box", "Bridal Gift", "Deal"],
    images: [
      { id: "p22-1", url: "/uploads/products/item-85.jpeg", alt: "Velvet Gift Set", isPrimary: true, sortOrder: 0 },
      { id: "p22-2", url: "/uploads/products/item-86.jpeg", alt: "Gift Hamper Inside", isPrimary: false, sortOrder: 1 },
      { id: "p22-3", url: "/uploads/products/item-05.jpeg", alt: "Earrings Set", isPrimary: false, sortOrder: 2 },
      { id: "p22-4", url: "/uploads/products/item-01.jpeg", alt: "Silk Lip Care", isPrimary: false, sortOrder: 3 },
    ],
    sellerId: "usr-admin-1",
    sellerName: "Veloura Atelier Official",
    sellerShopName: "Veloura Haute Atelier",
    sellerBasePrice: 480,
    adminProfitMargin: 15,
    createdAt: new Date().toISOString(),
  },
];

export function getVelouraProducts(): CatalogItem[] {
  return [...VELOURA_AUTHENTIC_PRODUCTS];
}
